class DataError(Exception):
    pass


class NotFoundError(DataError):
    pass
